# Generated by Django 4.2.3 on 2023-08-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='band',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='band',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='band',
            name='genres',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
