# Generated by Django 4.2.3 on 2023-08-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_remove_album_genres_remove_band_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='bandphoto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
