# Generated by Django 4.2.3 on 2023-08-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_alter_band_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='birth_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='musician',
            name='death_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='musician',
            name='profession',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.AddField(
            model_name='musician',
            name='profession',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
