# Generated by Django 4.2.3 on 2023-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_alter_musician_birth_date_alter_musician_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
