# Generated by Django 4.2.3 on 2023-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_band_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musician',
            name='birth_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musician',
            name='death_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
