# Generated by Django 4.2.3 on 2023-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_alter_album_name_alter_band_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, null=True),
        ),
    ]
