# Generated by Django 4.2.3 on 2023-08-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bands', '0010_alter_comment_album_alter_comment_band_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='album',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='band',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='musician',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='song',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_avatars'),
        ),
    ]
