# Generated by Django 4.2.3 on 2023-08-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0012_alter_comment_content_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='bands_comme_content_b0c13a_idx'),
        ),
    ]
