# Generated by Django 4.2.3 on 2023-08-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0023_musician_country_alter_album_likes_alter_band_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to=''),
        ),
    ]
