# Generated by Django 4.2.3 on 2023-08-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0025_alter_musician_options_profile_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name']},
        ),
    ]
