# Generated by Django 4.2.3 on 2023-08-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0027_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
